### PR TITLE
REM-990: Add validation for all rpc handlers

### PR DESCRIPTION
**Pull request by DeV1doR**
Implements issue REM-990.

### CODE REVIEW

**Comment by eugene-babichenko** [comment]
tests failed, return Internal Error for get_atomic_swap_info

**Comment by DeV1doR** [comment]
Reproduced

**Comment by DeV1doR** [comment]
Fixed

**Comment by Annitra** [comment]
1 get_block_number is missed;
2.  get_batch_status, get_atomic_swap_info, get_public_key_info for all tests return: Internal Error

**Comment by DeV1doR** [comment]
@Annitra 
1.
```
curl -X POST --data '{"jsonrpc": "2.0", "id": "test", "method": "get_block_number", "params": {}}' http://localhost:8080/
{"jsonrpc": "2.0", "id": "test", "result": 0}%
```
2. 
```
curl -X POST --data '{"jsonrpc": "2.0", "id": "test", "method": "get_batch_status", "params": {"id": "7518b111744fa8d54ba1e0cfd0dbea88c976bcbf1cd93caeba7af34b0bb5f3297720b6e84a5f862dadc40236957cf41d4dbe592639c2570e6506f4d7031663b3"}}' http://localhost:8080/
{"jsonrpc": "2.0", "id": "test", "result": "COMMITTED"}%
```
```
curl -X POST --data '{"jsonrpc": "2.0", "id": "test", "method": "get_atomic_swap_info", "params": {"swap_id": "0307d48890a5055879091986aadd820b37fdead29b9c567b0fb04b84970b6b09"}}' http://localhost:8080/
{"jsonrpc": "2.0", "id": "test", "result": {"sender_address": "11200722f1a3f5f766725d489619b2094a2b162e2613464020e7f9230daab3844b525e", "receiver_address": "112007484def48e1c6b77cf784aeabcac51222e48ae14f3821697f4040247ba01558b1", "amount": "100", "swap_id": "0307d48890a5055879091986aadd820b37fdead29b9c567b0fb04b84970b6b09", "created_at": 1548954602, "is_initiator": true, "sender_address_non_local": "0xe6ca0e7c974f06471759e9a05d18b538c5ced11e", "state": "OPENED", "email_address_encrypted_optional": "", "secret_lock": "", "secret_key": ""}}%
```
```
curl -X POST --data '{"jsonrpc": "2.0", "id": "test", "method": "get_public_key_info", "params": {"public_key_address": "11200722f1a3f5f766725d489619b2094a2b162e2613464020e7f9230daab3844b525e"}}' http://localhost:8080/
{"jsonrpc": "2.0", "error": {"code": -32603, "message": "Internal Error"}, "id": "test"}%
```

Only one error was reproduced

**Comment by Annitra** [comment]
curl -X POST --data '{"jsonrpc": "2.0", "id": "test", "method": "get_block_number", 
params: {
                id: '112007484def48e1c6b77cf784aeabcac51222e48ae14f3821697f4040247ba01558b1',
                sender_address: '11200759ba9b0d7ff93a3a8f6eb8e25fb5802d7caa8fad3d8bc19112b82f802a0cf9e8',
              receiver_address: '112007484def48e1c6b77cf784aeabcac51222e48ae14f3821697f4040247ba01558b1',
                start: 6,
                created_at: 1547824327,
                is_initiator: true,
               limit: 3,
               sender_address_non_local: '0xe6ca0e7c974f06471759e9a05d18b538c5ced11e',
               state: 'OPENED',
                email_address_encrypted_optional: '',
                secret_lock: '',
                secret_key: '',
             },}' http://localhost:8080/
{"jsonrpc": "2.0", "id": "test", "result": 0}%


Only "start" & "limit" are valid parameters

**Comment by DeV1doR** [comment]
@Annitra 
```
curl -X POST --data '{"jsonrpc": "2.0", "id": "test", "method": "get_block_number", "params": {"id": "112007484def48e1c6b77cf784aeabcac51222e48ae14f3821697f4040247ba01558b1", "sender_address": "11200759ba9b0d7ff93a3a8f6eb8e25fb5802d7caa8fad3d8bc19112b82f802a0cf9e8", "receiver_address": "112007484def48e1c6b77cf784aeabcac51222e48ae14f3821697f4040247ba01558b1", "start": 6, "created_at": 1547824327, "is_initiator": true, "limit": 3, "sender_address_non_local": "0xe6ca0e7c974f06471759e9a05d18b538c5ced11e", "state": "OPENED", "email_address_encrypted_optional": "", "secret_lock": "", "secret_key": ""}}' http://localhost:8080/
{"jsonrpc": "2.0", "error": {"code": -32602, "message": "Wrong params keys: ['sender_address_non_local', 'id', 'is_initiator', 'secret_key', 'limit', 'sender_address', 'state', 'start', 'created_at', 'email_address_encrypted_optional', 'receiver_address', 'secret_lock']"}, "id": "test"}%
```

**Pull request merged**
