### PR TITLE
REM-918: change charging storing public key fee to zero address

### PR DESCRIPTION
**Pull request by dmytrostriletskyi**
### Jira references
- Ticket (task) — https://remmeio.atlassian.net/browse/REM-918

### Implemented
— Change charging storing public key fee from specific address to zero address

### CODE REVIEW

**Comment by eugene-babichenko** [comment]
@ArtemFrantsiian Please make appropriate changes in JS library (fees are now stored in the same way as in atomic swaps).

**Comment by eugene-babichenko** [comment]
`AccountHandler()._check_signer_address` should not be called from atomic swap initialization. This function was initially intended to check if a user has the permission to **withdraw** from zero address - not to transfer to it. The current usage is wrong.

**Comment by eugene-babichenko** [comment]
You still have something left :) And please update the docs here.

image

**Comment by dmytrostriletskyi** [comment]
@eugene-babichenko, done!

**Pull request merged**
